# cc = g++
# target = oUT
# cflags = -g -Wall -Wextra -pedantic
# cxxfiles =	\
# 	driver.cpp	\
# 	myIO.cpp	\
# 	tree.cpp	\
# 	ThreadPool.cpp	\
# 	knn.cpp	\
# 	parallel_queries.cpp	\
# 
# all: $(target)
# 
# $(target): *.cpp *.hpp
# 	$(cc) $(cflags) $(cxxfiles) -o $(@) -lpthread
# 
# sidedriver: sidedriver.cpp
# 	$(cc) $(cflags) $(cxxfiles) sidedriver.cpp -o sidedriver -lpthread
# 
# clean:
# 	rm -rf $(target) sidedriver
